### ISSUE TITLE
max_df corresponds to < documents than min_df

### ISSUE THREAD

**Issue by alex-movila** [cdqa-suite/cdQA#224]
Hi,
I have a CSV file with 113 lines with title and only 1 paragraph. 
I show below only first line

title,paragraphs
"What We Do at LLL","['We do Custom Software, Software Testing, DevOps.']"
...

I get error:
    "max_df corresponds to < documents than min_df")
ValueError: max_df corresponds to < documents than min_df

Only max_df=0.85 is available to tune. I added min_df also and re-built the library but could not find good values in order to get good answers.

So there are several issues:
- no access to min_df
- good defaults when I have only 1 document
- can I solve using multiple documents?

**Comment by andrelmfarias** [comment]
Hi,

Indeed, `min_df` is a very important argument to be tuned with the `TfIdfRetriever`, we forgot to add it in our class. If you are interested in doing a PR with that (as you already re-built locally) you are more than welcome :). If not, I will be adding this feature to the next released version (and maybe other arguments to the `TfidfVectorizer` from sklearn.

Regarding the error, in order to fix it you have to set `max_df` to 1. `max_df` is the max fraction of documents where each specific token appears in order to have that token selected in the tf-idf matrix. If you have `max_df` set to a number that multiplied by number of documents is lower that  `min_df` no token will be selected by the `TfidfVectorizer` for the construction of the matrix. In your specific case your saying to the `TfidfVectorizer`: "please only take the tokens that appear in less than 0.85 * 1 documents and that appear in more than 1 document". 

You can refer to the official documentation of sklearn [`TfidfVectorizer`](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html) for more information

**Comment by mmehta-navomi** [comment]
Has this issue been resolved? I am getting the same error with my dataset.

**Comment by mmehta-navomi** [comment]
Has this issue been fixed? I've been receiving it with my data set which has a small number of paragraphs. Any help would be nice.

**Comment by andrelmfarias** [comment]
Hi @mmehta-navomi ,

Could you please try it by feeding the following arguments when initiating an instance of `QAPipeline`: `min_df=1`,  `max_df=1` ?

**Comment by mmehta-navomi** [comment]
Hey Andre, 
Thanks that seems to work, but does it have any impact on how the prediction will be made?

**Comment by andrelmfarias** [comment]
It can have some impact when there are several documents to retrieve from. 

As you have just a small number of paragraphs, there's no impact.

**Comment by TobiKoledoye** [comment]
> 
> 
> Hi @mmehta-navomi ,
> 
> Could you please try it by feeding the following arguments when initiating an instance of `QAPipeline`: `min_df=1`, `max_df=1` ?

how do i do this please? thanks

**Comment by TobiKoledoye** [comment]
> 
> 
> Hey Andre,
> Thanks that seems to work, but does it have any impact on how the prediction will be made?

how were you able to feed the arguments as he directed?

**Comment by mmehta-navomi** [comment]
@TobiKoledoye 
This is what I did `QAPipeline(reader='models/bert_qa_vCPU-sklearn.joblib', max_df=1, min_df=1)`
Hope this helps.
