### ISSUE TITLE
cdQA with other languages

### ISSUE THREAD

**Issue by Any0019** [cdqa-suite/cdQA#242]
Hello, I've been wondering how well does this package work with other (not eng) languages. Actually, I already tried cdQA package for my own QA system on rus and it doesn't work well at all. (I wasn't sure before, because of BERT working with 104 different languages).
So here is my question: may be I did smth wrong and this solution should be enough for different lang, or otherwise may be you can give me some tips or ideas how to build my own model in rus lang from scratch. Will be very grateful.

**Comment by andrelmfarias** [comment]
Hi @Any0019

Did you fine-tune the model on your own QA dataset with your language? The model we provided was fine-tuned on SQuAD 1.1, which is a QA dataset in English. In order to have a satisfactory performance, you should train BERT for QA in your own QA dataset if you are not using it for English.

You can also check our the discussion on #236
