### ISSUE TITLE
AttributeError: 'str' object has no attribute 'processor_train'

### ISSUE THREAD

**Issue by BojanKovachki** [cdqa-suite/cdQA#253]
I am trying to do transfer learning (fine-tuning), but I run into: 
**AttributeError: 'str' object has no attribute 'processor_train'**.

This is the code that produces the error (in Google Colab):

!pip install cdqa
from cdqa.pipeline.cdqa_sklearn import QAPipeline
cdqa_pipeline = QAPipeline(reader='./data/bert_qa_vCPU-sklearn.joblib')
QAPipeline.fit_reader('./data/my-train-data.json')

 - OS: openSUSE Leap 15.1
 - Browser: chrome

Am I doing something wrong? 
Is this how one is supposed to do fine-tuning with cdQA or not? 
Furthermore, does this code (when working fine) produce a new .joblib file or is that part missing in my code?

I want to use the pretrained BERT model (CPU version) and train it on my own data (by doing transfer learning). My data is in the same format as the SQUADv1.1 dataset.

**Comment by andrelmfarias** [comment]
You are getting this error because you are calling `fit_reader` on the class, not on the object.

> Furthermore, does this code (when working fine) produce a new .joblib file or is that part missing in my code?

No, it doesn't. If you want to save the Reader model in a new `.joblib` file you should run the following cell (or follow our tutorials [here](https://github.com/cdqa-suite/cdQA#notebook-examples))


```
joblib.dump(cdqa_pipeline.reader, path_to_save_joblib)
```

**Comment by BojanKovachki** [comment]
@andrelmfarias, thank you for your response!

I just noticed my silly mistake, sorry. Since I am new to cdQA, I'd like to ask you, do you have a tutorial for doing transfer learning (fine-tuning) with your suite (for example, for editing just certain layers of the model, etc.)? 

Thanks again!

**Comment by andrelmfarias** [comment]
@BojanKovachki,

In order to fine-tune the Reader model (BERT), i.e. do transfer learning with cdQA, you should follow our official tutorials or the code you posted above (after correcting the mistake).

What you propose, editing / modifying layers in the model, is not considered transfer learning in my view, as it changes the model architecture. 

Our suite does not offer this support as we use PyTorch models provided by HuggingFace.

If you are interested in changing the model architecture you should load the model from Hugging Face and modify it using PyTorch code, but I think it's pretty complex though. Moreover, if you want to integrate the modified model with cdQA it might be a bit tough... You should assure the inputs and outputs from your model and Hugging Face's BERT are the same, and the model is loaded on a similar fashion.

**Comment by BojanKovachki** [comment]
Thank you @andrelmfarias, things are more clear now!

I tried to fine-tune you pretrained BERT model (CPU version), but I am getting this as a result:

**Training beyond specified 't_total'. Learning rate multiplier set to 0.0. Please set 't_total' of WarmupLinearSchedule correctly.**

I have noticed that someone had the same issue, and you mentioned that it might be because of the lack of data... 
What I am trying to do is the following: 
I have a user manual, I am annotating it with the cdQA-annotator and then I am trying to do transfer learning...

Do you think it's possible to do proper transfer learning for just 1 document (I noticed in some of the closed issues that someone has done it already, although it did not produce good results, so I thought to give it a try)?

BTW I have also noticed the the cdQA-annotator is not creating question ids in the .json file it produces.. is this supposed to be this way or not, because there are question ids in the SQuADv1.1 dataset...

**Comment by andrelmfarias** [comment]
> Do you think it's possible to do proper transfer learning for just 1 document (I noticed in some of the closed issues that someone has done it already, although it did not produce good results, so I thought to give it a try)?

Honestly, I don't think it's worthy. The model won't learn with only one sample. It's better just to use the pre-trained model on SQuAD 1.1, it usually performs pretty good. For instance, I used cdQA for a project where we did not have enough documents to train, so we just used the model fine-tuned on SQuAD.

> BTW I have also noticed the the cdQA-annotator is not creating question ids in the .json file it produces.. is this supposed to be this way or not, because there are question ids in the SQuADv1.1 dataset...

You are right, we have opened an issue about it: https://github.com/cdqa-suite/cdQA-annotator/issues/29 . We have just forgotten to solve it.

For now, I advise you to run the following snippet in order to add the ids:
```
import uuid
for doc in annotated_dataset['data']:
    for p in doc['paragraphs']:
        for qa in p['qas']:
            qa['id'] = str(uuid.uuid4())
```

**Comment by BojanKovachki** [comment]
Thanks again @andrelmfarias!

One more question.. is it possible to only use the reader (without the retriever)?
If I have only 1 document that I am querying, it makes no sense to use the retriever, right?

Will this have any effect on the precision? Will the model work better if I only have 1 document and I am not using the retriever at all? And is this possible at the moment with cdQA?

Your help is greatly appreciated.

**Comment by andrelmfarias** [comment]
> One more question.. is it possible to only use the reader (without the retriever)?
If I have only 1 document that I am querying, it makes no sense to use the retriever, right?
>
>Will this have any effect on the precision? Will the model work better if I only have 1 document and I am not using the retriever at all? And is this possible at the moment with cdQA?

It's possible to do it, but it's a bit tricky and it will require more code than using the pipeline. We created the pipeline object with the purpose of wrapping this amount of code to facilitate the work of cdQA users. The results and time execution will be exactly the same. So I even if you have only one document, it's better to use the whole pipeline.
