### ISSUE TITLE
CDQA Features/Limitations and need clarifications for technicial documents.

### ISSUE THREAD

**Issue by AIMLTest** [cdqa-suite/cdQA#300]
Hi,

I am having some basic questions in CDQA project, can you please check once and let me know.

And am also trying similar poc, We have many tech documents like it could be manuals for the problem resolutions details. I have taken approach like extracting all Header tags using beautifulsoup and based on header tags we will create training dataset and providing complete answer paragraph accordingly. I am looking if any better solution if possible.

1. Is Knowledge graphs concept implemented and if it's may i know the details.
2. cdQA-annotator,I think we should use in closed domain projects and need to annotate data from scratch and also to be manually?
3. May i know how much manual required efforts for new documents and we have lot of technical documents. And my point is how much we should train question and answer,if we should do almost everything then again it could be traditional chatbots concept.
4. Can we integrate to our own customized-Ui and chatbots.

Thanks
Sharath

**Comment by andrelmfarias** [comment]
Hi,

1. cdQA is not knowledge graph based. You can check all the information about how the system works under the hood on [our article on Medium](https://towardsdatascience.com/how-to-create-your-own-question-answering-system-easily-with-python-2ef8abc8eb5) or you can check [my presentation](https://blog.feedly.com/nlp-breakfast-9-closed-domain-question-answering/) on the Feedly's NLP Breakfast. Both links are also found on our readme.

2. The annotator is used to annotate data for 2 main reasons: (i) Evaluate the efficiency of the model on your specific data, (ii) Fine-tune the reader model on your specific text data (please refer to our readme to see how you can fine-tune the reader on the annotated data).

3. It really depends. For some types of documents you don't need to fine-tune the reader, it already performs well with the pre-trained model on SQuAD. For others, you should annotate some pairs of questions answers and train the Reader on it so that the model learns to generalize in your specific domain. Anyway, you should at least annotate some data to at least evaluate its performance on your data.

4. Yes you can, you just need to set up a REST API running in the backend. We show how to fo it in our README with Flask, but be aware that flask is not made for production, only for development, you should use other frameworks to run the app in production, such as gunicorn.
