### ISSUE TITLE
Can we do train_test_split() on SQuAD-like json file?

### ISSUE THREAD

**Issue by n0thingLLM** [cdqa-suite/cdQA#43]
We might use directly sklearn [`train_test_split`](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html).

@andrelmfarias as discussed, to be done after annotation.

**Comment by kusumlata123** [comment]
> We actually don't need this because we are not fine-tuning the reader on our annotated dataset (we only annotate it for evaluation atm).
> 
> If later our dataset annotations size increases and justify a fine-tuning to gain in performance, we will do:
> 
> ```python
> from sklearn.model_selection import train_test_split
>     
> train, test = train_test_split(json_data) # json_data is the annotated dataset
> ```

After applying this I we want to save as train.json and test.json then what should be do?

**Comment by harshgeek4coder** [comment]
@fmikaelian @kusumlata123 @andrelmfarias 
So I was also dealing with this kind of an issue - since the free tier of GPU-based instances might not be able to extract features of huge SQuaD format datasets. I tried to work around with something relevant to perform train_test_split and maintain SQuAD format  - 
- if you take a look at this method, there is a certain format how the split file needs to be before it can be used to extract features - https://github.com/huggingface/transformers/blob/main/src/transformers/data/processors/squad.py#L607


- The format of the split data needs to be in dict type (so json format is a must) and also the context,qas needs to be nested in ```data``` key of the split json file (much similar to squad dataset samples)

My implementation - 


```
import json
from sklearn.model_selection import train_test_split

# Load JSON file
with open('data.json', 'r') as file:
    json_data = json.load(file)
    
# Split the data into train and test subsets
train_data, test_data = train_test_split(json_data['data'], test_size=0.2, random_state=42)

# Create a new dictionary with train and test subsets
split_data = {
    'version': data['version'],
    'data': train_data
}

# Save the train and test subsets as separate JSON files
with open('train_reduced1.json', 'w') as train_file:
    json.dump(split_data, train_file)


```

Feel free to modify it at your convenience.
Cheers
